from __future__ import annotations

from datetime import date, datetime

from app.models.movie import Movie, MovieAnalytics
from app.services.hype_calculator import HypeCalculator


MOVIE_CATALOG = [
    {
        "tmdb_id": 8725851,
        "slug": "oppenheimer",
        "title": "Oppenheimer",
        "release_date": date(2023, 7, 21),
        "status": "released",
        "poster_url": "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80",
        "backdrop_url": "https://images.unsplash.com/photo-1460881680858-30d872d5b530?auto=format&fit=crop&w=1600&q=80",
        "overview": "Christopher Nolans historical epic turned sustained theatrical demand into a long-tail event movie with unusual cultural reach.",
        "genres": ["Drama", "History", "Thriller"],
        "tmdb_popularity": 83.2,
        "youtube_views": 52700000,
        "youtube_likes": 1304000,
        "youtube_comments": 64300,
        "google_trends_score": 81,
        "x_mentions": 198000,
        "reddit_mentions": 35600,
        "sentiment_score": 0.9,
        "sentiment_breakdown": {"positive": 81, "neutral": 13, "negative": 6},
        "momentum_score": 0.68,
        "trailer_url": "https://www.youtube.com/watch?v=uYPbbksJxIg",
        "predicted_opening_weekend_usd": 82400000,
        "predicted_domestic_total_usd": 330100000,
    },
    {
        "tmdb_id": 8725852,
        "slug": "barbie",
        "title": "Barbie",
        "release_date": date(2023, 7, 21),
        "status": "released",
        "poster_url": "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=80",
        "backdrop_url": "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1600&q=80",
        "overview": "A maximalist comedy with breakout meme energy, massive social carry, and one of the clearest examples of a movie becoming an online aesthetic.",
        "genres": ["Comedy", "Fantasy", "Adventure"],
        "tmdb_popularity": 89.1,
        "youtube_views": 71300000,
        "youtube_likes": 1722000,
        "youtube_comments": 118500,
        "google_trends_score": 88,
        "x_mentions": 412000,
        "reddit_mentions": 48200,
        "sentiment_score": 0.84,
        "sentiment_breakdown": {"positive": 76, "neutral": 15, "negative": 9},
        "momentum_score": 0.74,
        "trailer_url": "https://www.youtube.com/watch?v=pBk4NYhWNMM",
        "predicted_opening_weekend_usd": 162000000,
        "predicted_domestic_total_usd": 636200000,
    },
    {
        "tmdb_id": 8725853,
        "slug": "spider-man-no-way-home",
        "title": "Spider-Man: No Way Home",
        "release_date": date(2021, 12, 17),
        "status": "released",
        "poster_url": "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?auto=format&fit=crop&w=800&q=80",
        "backdrop_url": "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1600&q=80",
        "overview": "A spoiler-sensitive franchise event that translated nostalgia, secrecy, and fandom speculation into extraordinary pre-release attention.",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "tmdb_popularity": 92.5,
        "youtube_views": 121400000,
        "youtube_likes": 4200000,
        "youtube_comments": 289000,
        "google_trends_score": 93,
        "x_mentions": 525000,
        "reddit_mentions": 71400,
        "sentiment_score": 0.87,
        "sentiment_breakdown": {"positive": 79, "neutral": 12, "negative": 9},
        "momentum_score": 0.71,
        "trailer_url": "https://www.youtube.com/watch?v=JfVOs4VSpmA",
        "predicted_opening_weekend_usd": 260100000,
        "predicted_domestic_total_usd": 804800000,
    },
    {
        "tmdb_id": 8725854,
        "slug": "top-gun-maverick",
        "title": "Top Gun: Maverick",
        "release_date": date(2022, 5, 27),
        "status": "released",
        "poster_url": "https://images.unsplash.com/photo-1504198458649-3128b932f49b?auto=format&fit=crop&w=800&q=80",
        "backdrop_url": "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1600&q=80",
        "overview": "A word-of-mouth juggernaut that converted legacy brand recognition into repeat attendance and unusually durable audience enthusiasm.",
        "genres": ["Action", "Drama"],
        "tmdb_popularity": 79.4,
        "youtube_views": 46200000,
        "youtube_likes": 1108000,
        "youtube_comments": 51200,
        "google_trends_score": 73,
        "x_mentions": 146000,
        "reddit_mentions": 21900,
        "sentiment_score": 0.91,
        "sentiment_breakdown": {"positive": 83, "neutral": 11, "negative": 6},
        "momentum_score": 0.62,
        "trailer_url": "https://www.youtube.com/watch?v=giXco2jaZ_4",
        "predicted_opening_weekend_usd": 126700000,
        "predicted_domestic_total_usd": 718700000,
    },
    {
        "tmdb_id": 8725855,
        "slug": "avatar-the-way-of-water",
        "title": "Avatar: The Way of Water",
        "release_date": date(2022, 12, 16),
        "status": "released",
        "poster_url": "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=800&q=80",
        "backdrop_url": "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1600&q=80",
        "overview": "James Camerons sequel leaned on spectacle-first marketing and global curiosity, with a slower but powerful momentum curve.",
        "genres": ["Sci-Fi", "Adventure", "Fantasy"],
        "tmdb_popularity": 81.6,
        "youtube_views": 39800000,
        "youtube_likes": 904000,
        "youtube_comments": 74600,
        "google_trends_score": 78,
        "x_mentions": 189000,
        "reddit_mentions": 30100,
        "sentiment_score": 0.79,
        "sentiment_breakdown": {"positive": 70, "neutral": 18, "negative": 12},
        "momentum_score": 0.67,
        "trailer_url": "https://www.youtube.com/watch?v=d9MyW72ELq0",
        "predicted_opening_weekend_usd": 134100000,
        "predicted_domestic_total_usd": 684100000,
    },
    {
        "tmdb_id": 8725856,
        "slug": "inside-out-2",
        "title": "Inside Out 2",
        "release_date": date(2024, 6, 14),
        "status": "released",
        "poster_url": "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80",
        "backdrop_url": "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1600&q=80",
        "overview": "A family four-quadrant sequel that blended nostalgia with fresh character hooks and quickly became a broad audience favorite.",
        "genres": ["Animation", "Family", "Comedy"],
        "tmdb_popularity": 87.3,
        "youtube_views": 34700000,
        "youtube_likes": 1087000,
        "youtube_comments": 39300,
        "google_trends_score": 82,
        "x_mentions": 172000,
        "reddit_mentions": 28400,
        "sentiment_score": 0.92,
        "sentiment_breakdown": {"positive": 84, "neutral": 11, "negative": 5},
        "momentum_score": 0.7,
        "trailer_url": "https://www.youtube.com/watch?v=LEjhY15eCx0",
        "predicted_opening_weekend_usd": 154200000,
        "predicted_domestic_total_usd": 652900000,
    },
    {
        "tmdb_id": 872585,
        "slug": "dune-part-two",
        "title": "Dune: Part Two",
        "release_date": date(2024, 3, 1),
        "status": "released",
        "poster_url": "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
        "backdrop_url": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
        "overview": "Paul Atreides rallies allies across Arrakis as the war for spice turns global attention into pure spectacle.",
        "genres": ["Sci-Fi", "Adventure", "Drama"],
        "tmdb_popularity": 91.3,
        "youtube_views": 38500000,
        "youtube_likes": 912000,
        "youtube_comments": 54800,
        "google_trends_score": 89,
        "x_mentions": 184000,
        "reddit_mentions": 28600,
        "sentiment_score": 0.82,
        "sentiment_breakdown": {"positive": 72, "neutral": 18, "negative": 10},
        "momentum_score": 0.91,
        "trailer_url": "https://www.youtube.com/watch?v=Way9Dexny3w",
        "predicted_opening_weekend_usd": 118000000,
        "predicted_domestic_total_usd": 355000000,
    },
    {
        "tmdb_id": 1022789,
        "slug": "the-batman-part-ii",
        "title": "The Batman Part II",
        "release_date": date(2026, 10, 2),
        "status": "announced",
        "poster_url": "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
        "backdrop_url": "https://images.unsplash.com/photo-1520034475321-cbe63696469a?auto=format&fit=crop&w=1600&q=80",
        "overview": "Gotham gets darker as a new criminal network exploits the citys obsession with masked justice.",
        "genres": ["Action", "Crime", "Thriller"],
        "tmdb_popularity": 85.7,
        "youtube_views": 27100000,
        "youtube_likes": 801000,
        "youtube_comments": 68900,
        "google_trends_score": 84,
        "x_mentions": 241000,
        "reddit_mentions": 33500,
        "sentiment_score": 0.77,
        "sentiment_breakdown": {"positive": 68, "neutral": 20, "negative": 12},
        "momentum_score": 0.86,
        "trailer_url": "https://www.youtube.com/watch?v=mqqft2x_Aa4",
        "predicted_opening_weekend_usd": 132000000,
        "predicted_domestic_total_usd": 402000000,
    },
    {
        "tmdb_id": 299536,
        "slug": "avengers-secret-wars",
        "title": "Avengers: Secret Wars",
        "release_date": date(2027, 5, 7),
        "status": "announced",
        "poster_url": "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80",
        "backdrop_url": "https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=1600&q=80",
        "overview": "Marvels multiverse event movie arrives with franchise-scale expectations and nonstop online speculation.",
        "genres": ["Action", "Sci-Fi", "Fantasy"],
        "tmdb_popularity": 97.4,
        "youtube_views": 44100000,
        "youtube_likes": 1201000,
        "youtube_comments": 101400,
        "google_trends_score": 94,
        "x_mentions": 423000,
        "reddit_mentions": 58100,
        "sentiment_score": 0.74,
        "sentiment_breakdown": {"positive": 64, "neutral": 23, "negative": 13},
        "momentum_score": 0.94,
        "trailer_url": "https://www.youtube.com/watch?v=example-secret-wars",
        "predicted_opening_weekend_usd": 195000000,
        "predicted_domestic_total_usd": 610000000,
    },
    {
        "tmdb_id": 447365,
        "slug": "guardians-of-the-galaxy-rebirth",
        "title": "Guardians of the Galaxy: Rebirth",
        "release_date": date(2026, 7, 17),
        "status": "upcoming",
        "poster_url": "https://images.unsplash.com/photo-1499364615650-ec38552f4f34?auto=format&fit=crop&w=800&q=80",
        "backdrop_url": "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1600&q=80",
        "overview": "A new team inherits the mixtape energy, cosmic chaos, and impossible expectations of the Guardians brand.",
        "genres": ["Action", "Comedy", "Sci-Fi"],
        "tmdb_popularity": 76.9,
        "youtube_views": 22400000,
        "youtube_likes": 498000,
        "youtube_comments": 32200,
        "google_trends_score": 71,
        "x_mentions": 109000,
        "reddit_mentions": 17600,
        "sentiment_score": 0.71,
        "sentiment_breakdown": {"positive": 63, "neutral": 24, "negative": 13},
        "momentum_score": 0.66,
        "trailer_url": "https://www.youtube.com/watch?v=example-guardians",
        "predicted_opening_weekend_usd": 101000000,
        "predicted_domestic_total_usd": 284000000,
    },
    {
        "tmdb_id": 901362,
        "slug": "spider-man-new-day",
        "title": "Spider-Man: New Day",
        "release_date": date(2026, 12, 18),
        "status": "announced",
        "poster_url": "https://images.unsplash.com/photo-1518733057094-95b53143d2a7?auto=format&fit=crop&w=800&q=80",
        "backdrop_url": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1600&q=80",
        "overview": "Peter Parker faces a reset era, and the internet is watching every casting rumor and set leak in real time.",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "tmdb_popularity": 88.4,
        "youtube_views": 31200000,
        "youtube_likes": 978000,
        "youtube_comments": 80200,
        "google_trends_score": 90,
        "x_mentions": 356000,
        "reddit_mentions": 44200,
        "sentiment_score": 0.8,
        "sentiment_breakdown": {"positive": 70, "neutral": 19, "negative": 11},
        "momentum_score": 0.9,
        "trailer_url": "https://www.youtube.com/watch?v=example-spiderman",
        "predicted_opening_weekend_usd": 171000000,
        "predicted_domestic_total_usd": 520000000,
    },
    {
        "tmdb_id": 938614,
        "slug": "inside-out-3",
        "title": "Inside Out 3",
        "release_date": date(2026, 6, 12),
        "status": "upcoming",
        "poster_url": "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80",
        "backdrop_url": "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1600&q=80",
        "overview": "Pixar returns to Rileys inner world with a family-four-quadrant release that is quietly building major momentum.",
        "genres": ["Animation", "Family", "Comedy"],
        "tmdb_popularity": 74.8,
        "youtube_views": 19800000,
        "youtube_likes": 610000,
        "youtube_comments": 28700,
        "google_trends_score": 76,
        "x_mentions": 91000,
        "reddit_mentions": 22100,
        "sentiment_score": 0.88,
        "sentiment_breakdown": {"positive": 78, "neutral": 16, "negative": 6},
        "momentum_score": 0.72,
        "trailer_url": "https://www.youtube.com/watch?v=example-insideout",
        "predicted_opening_weekend_usd": 94000000,
        "predicted_domestic_total_usd": 330000000,
    },
    {
        "tmdb_id": 8725857,
        "slug": "superman-legacy",
        "title": "Superman: Legacy",
        "release_date": date(2026, 8, 14),
        "status": "upcoming",
        "poster_url": "https://images.unsplash.com/photo-1542204625-de293a2f8ff0?auto=format&fit=crop&w=800&q=80",
        "backdrop_url": "https://images.unsplash.com/photo-1502134249126-9f3755a50d78?auto=format&fit=crop&w=1600&q=80",
        "overview": "A fresh DC reset title carrying heavy curiosity from both comic loyalists and general audiences waiting for a new tone.",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "tmdb_popularity": 90.2,
        "youtube_views": 28600000,
        "youtube_likes": 854000,
        "youtube_comments": 69300,
        "google_trends_score": 87,
        "x_mentions": 266000,
        "reddit_mentions": 39800,
        "sentiment_score": 0.76,
        "sentiment_breakdown": {"positive": 67, "neutral": 20, "negative": 13},
        "momentum_score": 0.88,
        "trailer_url": "https://www.youtube.com/watch?v=example-superman",
        "predicted_opening_weekend_usd": 148000000,
        "predicted_domestic_total_usd": 438000000,
    },
    {
        "tmdb_id": 8725858,
        "slug": "the-fantastic-four-first-steps",
        "title": "The Fantastic Four: First Steps",
        "release_date": date(2026, 11, 6),
        "status": "upcoming",
        "poster_url": "https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&w=800&q=80",
        "backdrop_url": "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=1600&q=80",
        "overview": "Marvels first family returns with reboot-level stakes, a casting-driven conversation cycle, and unusually wide fan scrutiny.",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "tmdb_popularity": 93.1,
        "youtube_views": 36100000,
        "youtube_likes": 990000,
        "youtube_comments": 84400,
        "google_trends_score": 91,
        "x_mentions": 384000,
        "reddit_mentions": 54700,
        "sentiment_score": 0.73,
        "sentiment_breakdown": {"positive": 64, "neutral": 22, "negative": 14},
        "momentum_score": 0.92,
        "trailer_url": "https://www.youtube.com/watch?v=example-fantastic4",
        "predicted_opening_weekend_usd": 176000000,
        "predicted_domestic_total_usd": 506000000,
    },
    {
        "tmdb_id": 8725859,
        "slug": "shrek-5",
        "title": "Shrek 5",
        "release_date": date(2027, 3, 26),
        "status": "announced",
        "poster_url": "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
        "backdrop_url": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
        "overview": "A nostalgia-heavy animated revival with broad meme potential and a family audience that still strongly recognizes the brand.",
        "genres": ["Animation", "Comedy", "Family"],
        "tmdb_popularity": 79.2,
        "youtube_views": 17900000,
        "youtube_likes": 533000,
        "youtube_comments": 42100,
        "google_trends_score": 75,
        "x_mentions": 211000,
        "reddit_mentions": 26600,
        "sentiment_score": 0.8,
        "sentiment_breakdown": {"positive": 73, "neutral": 17, "negative": 10},
        "momentum_score": 0.81,
        "trailer_url": "https://www.youtube.com/watch?v=example-shrek5",
        "predicted_opening_weekend_usd": 97000000,
        "predicted_domestic_total_usd": 302000000,
    },
    {
        "tmdb_id": 8725860,
        "slug": "toy-story-5",
        "title": "Toy Story 5",
        "release_date": date(2027, 6, 18),
        "status": "announced",
        "poster_url": "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=800&q=80",
        "backdrop_url": "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1600&q=80",
        "overview": "Pixars next franchise return is still early, but brand familiarity alone is producing strong baseline conversation and curiosity.",
        "genres": ["Animation", "Adventure", "Family"],
        "tmdb_popularity": 77.5,
        "youtube_views": 14300000,
        "youtube_likes": 418000,
        "youtube_comments": 27800,
        "google_trends_score": 69,
        "x_mentions": 137000,
        "reddit_mentions": 24100,
        "sentiment_score": 0.83,
        "sentiment_breakdown": {"positive": 75, "neutral": 16, "negative": 9},
        "momentum_score": 0.77,
        "trailer_url": "https://www.youtube.com/watch?v=example-toystory5",
        "predicted_opening_weekend_usd": 109000000,
        "predicted_domestic_total_usd": 336000000,
    },
]

SEEDED_MOVIE_SLUGS = {movie["slug"] for movie in MOVIE_CATALOG}


def build_movie_payloads(snapshot_date: date | None = None) -> list[dict]:
    active_snapshot_date = snapshot_date or date.today()
    payloads = []

    for movie in MOVIE_CATALOG:
        analytics_payload = {
            "youtube_views": movie["youtube_views"],
            "youtube_likes": movie["youtube_likes"],
            "youtube_comments": movie["youtube_comments"],
            "google_trends_score": movie["google_trends_score"],
            "twitter_mentions": movie["x_mentions"],
            "reddit_mentions": movie["reddit_mentions"],
            "sentiment_score": movie["sentiment_score"],
            "momentum_score": movie["momentum_score"],
        }
        buzz_score = HypeCalculator.calculate_buzz_score(analytics_payload)
        hype_score = HypeCalculator.calculate_hype_score(
            analytics_payload,
            datetime.combine(movie["release_date"], datetime.min.time()),
        )
        payloads.append(
            {
                **movie,
                "snapshot_date": active_snapshot_date,
                "updated_at": datetime.utcnow(),
                "buzz_score": buzz_score,
                "hype_score": hype_score,
                "social_mentions": movie["x_mentions"] + movie["reddit_mentions"],
            }
        )

    return payloads


def build_models(snapshot_date: date | None = None) -> list[tuple[Movie, MovieAnalytics]]:
    models = []
    for payload in build_movie_payloads(snapshot_date=snapshot_date):
        movie = Movie(
            tmdb_id=payload["tmdb_id"],
            slug=payload["slug"],
            title=payload["title"],
            release_date=payload["release_date"],
            status=payload["status"],
            poster_url=payload["poster_url"],
            backdrop_url=payload["backdrop_url"],
            overview=payload["overview"],
            genres=payload["genres"],
            tmdb_popularity=payload["tmdb_popularity"],
        )
        analytics = MovieAnalytics(
            snapshot_label="latest",
            snapshot_date=payload["snapshot_date"],
            youtube_views=payload["youtube_views"],
            youtube_likes=payload["youtube_likes"],
            youtube_comments=payload["youtube_comments"],
            google_trends_score=payload["google_trends_score"],
            x_mentions=payload["x_mentions"],
            reddit_mentions=payload["reddit_mentions"],
            sentiment_score=payload["sentiment_score"],
            sentiment_positive=payload["sentiment_breakdown"]["positive"],
            sentiment_neutral=payload["sentiment_breakdown"]["neutral"],
            sentiment_negative=payload["sentiment_breakdown"]["negative"],
            momentum_score=payload["momentum_score"],
            buzz_score=payload["buzz_score"],
            hype_score=payload["hype_score"],
            predicted_opening_weekend_usd=payload["predicted_opening_weekend_usd"],
            predicted_domestic_total_usd=payload["predicted_domestic_total_usd"],
            trailer_url=payload["trailer_url"],
            last_updated=payload["updated_at"],
        )
        models.append((movie, analytics))
    return models
