import { expect, test } from '@playwright/test'

test('guest favourites, follow-up constraints, and different picks', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/recommendations')
  await page.getByLabel('Favourite movies').fill('Chat Movie 00')
  await page.getByRole('button', { name: 'Add Chat Movie 00 (2020)' }).click()
  await page.getByLabel('Message Movie Match').fill('English science fiction under two hours')
  await page.getByRole('button', { name: 'Send message' }).click()
  const results = page.getByRole('region', { name: 'Recommended movies' })
  await expect(results).toBeVisible()
  await expect(results.getByRole('heading', { name: 'Chat Movie 00', exact: true })).toHaveCount(0)
  await expect(results.getByText('Shares Science Fiction with Chat Movie 00.').first()).toBeVisible()
  await page.getByLabel('Message Movie Match').fill('No horror')
  await page.getByRole('button', { name: 'Send message' }).click()
  await expect(page.getByText('Excluding: Horror')).toBeVisible()
  await expect(page.getByLabel('Language', { exact: true })).toHaveValue('English')
  await expect(page.getByLabel('Maximum runtime (minutes)')).toHaveValue('119')
  await expect(results.getByRole('heading', { name: 'Chat Movie 02', exact: true })).toHaveCount(0)
  const first = await results.locator('h3').allTextContents()
  await page.getByRole('button', { name: 'Show more', exact: true }).click()
  await expect(results.getByRole('heading', { name: 'Chat Movie 08', exact: true })).toBeVisible()
  expect((await results.locator('h3').allTextContents()).every(title => !first.includes(title))).toBeTruthy()
  expect(errors).toEqual([])
})

test('unknown requests clarify and impossible filters return no movies', async ({ page }) => {
  await page.goto('/recommendations')
  await page.getByLabel('Message Movie Match').fill('Write an essay about computers')
  await page.getByRole('button', { name: 'Send message' }).click()
  await expect(page.getByRole('log').getByText(/don't yet understand/)).toBeVisible()
  await page.getByLabel('Message Movie Match').fill('Japanese horror under 10 minutes')
  await page.getByRole('button', { name: 'Send message' }).click()
  await expect(page.getByRole('log').getByText(/No more catalog movies/)).toBeVisible()
  await expect(page.getByRole('region', { name: 'Recommended movies' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Start a new chat' }).click()
  await expect(page.getByLabel('Language', { exact: true })).toHaveValue('')
})

test('account taste survives reload and dismissal can be undone', async ({ page }) => {
  await page.goto('/watchlist')
  await page.getByRole('button', { name: 'New here? Create an account' }).click()
  await page.getByLabel('Username', { exact: true }).fill(`taste_${Date.now()}`)
  await page.getByLabel('Password', { exact: true }).fill('a-long-private-test-password')
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Your watchlist', exact: true })).toBeVisible()
  await page.goto('/recommendations')
  await page.getByLabel('Favourite movies').fill('Chat Movie 00')
  await page.getByRole('button', { name: 'Add Chat Movie 00 (2020)' }).click()
  await expect(page.getByRole('button', { name: 'Remove favourite Chat Movie 00' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Remove favourite Chat Movie 00' })).toBeVisible()
  await page.getByRole('button', { name: 'Find my movies' }).click()
  await page.getByRole('button', { name: 'Dismiss Chat Movie 01', exact: true }).click()
  await page.getByText('Dismissed movies', { exact: true }).click()
  await expect(page.getByRole('button', { name: 'Undo dismissal: Chat Movie 01' })).toBeVisible()
  await page.reload()
  await page.getByText('Dismissed movies', { exact: true }).click()
  await page.getByRole('button', { name: 'Undo dismissal: Chat Movie 01' }).click()
  await expect(page.getByText('Dismissed movies', { exact: true })).toHaveCount(0)
})

test('mobile chat fits the viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/recommendations')
  await page.getByLabel('Message Movie Match').fill('science fiction')
  await page.getByRole('button', { name: 'Send message' }).click()
  await expect(page.getByRole('heading', { name: 'Your shortlist' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('unconfigured AI is visible and cannot be enabled', async ({ page }) => {
  await page.goto('/recommendations')
  await expect(page.getByLabel('Interpret my request')).toBeDisabled()
  await expect(page.getByText('Request interpretation is not configured on this server. Catalog mode is available.')).toBeVisible()
})

test('AI is opt-in and unavailable responses retain current filters', async ({ page }) => {
  await page.goto('/watchlist')
  await page.getByRole('button', { name: 'New here? Create an account' }).click()
  await page.getByLabel('Username', { exact: true }).fill(`ai_${Date.now()}`)
  await page.getByLabel('Password', { exact: true }).fill('a-long-private-test-password')
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Your watchlist', exact: true })).toBeVisible()
  await page.route('**/api/assistant/coverage', route => route.fulfill({json:{released_movies:10,with_runtime:10,with_language:10,ai_available:true}}))
  await page.goto('/recommendations')
  await expect(page.getByLabel('Interpret my request')).not.toBeChecked()
  await page.getByLabel('Genre', { exact: true }).selectOption('Science Fiction')
  await page.getByLabel('Interpret my request').check()
  let captured: Record<string, unknown> = {}
  await page.route('**/api/assistant/chat', async route => {
    captured = route.request().postDataJSON()
    await route.fulfill({json:{reply:'Request interpretation is temporarily unavailable. Your filters are unchanged.', filters:captured.filters, items:[], mode:'ai-unavailable', needs_clarification:true}})
  })
  await page.getByLabel('Message Movie Match').fill('Something with a sense of wonder')
  await page.getByRole('button', { name: 'Send message' }).click()
  await expect(page.getByRole('log').getByText(/Request interpretation is temporarily unavailable/)).toBeVisible()
  expect(captured.use_ai).toBe(true)
  await expect(page.getByLabel('Genre', { exact: true })).toHaveValue('Science Fiction')
})
