import { test, expect } from '@playwright/test'

test('recovery code resets password and is consumed', async ({ page }) => {
  const username = `recover_${Date.now()}`
  await page.goto('/watchlist')
  await page.getByRole('button', { name: 'New here? Create an account' }).click()
  await page.getByLabel('Username', { exact: true }).fill(username)
  await page.getByLabel('Password', { exact: true }).fill('test-password-long-123')
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await page.getByRole('link', { name: 'Account security', exact: true }).click()
  await page.getByLabel('Current password').fill('test-password-long-123')
  await page.getByRole('button', { name: 'Generate recovery code' }).click()
  const code = page.locator('[role="status"] code')
  await expect(code).toBeVisible()
  const recovery = await code.innerText()
  await page.getByRole('link', { name: 'Back to watchlist' }).click()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await page.getByRole('link', { name: 'Forgot your password? Use a recovery code' }).click()
  await expect(page).toHaveURL(/account-security$/)
  await page.getByLabel('Username', { exact: true }).fill(username)
  await page.getByLabel('Recovery code', { exact: true }).fill(recovery)
  await page.getByLabel('New password').fill('replacement-password-123')
  await page.getByRole('button', { name: 'Reset password', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Password reset')
  await page.getByRole('link', { name: 'Back to sign in' }).click()
  await expect(page).toHaveURL(/watchlist$/)
  await page.getByLabel('Username', { exact: true }).fill(username)
  await page.getByLabel('Password', { exact: true }).fill('replacement-password-123')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Your watchlist', exact: true })).toBeVisible()
})
